### ISSUE TITLE
Looking up montreal quebec causes blank screen

### ISSUE THREAD

**Issue by dsert1** [61040-ddag/neighborhoods#4]
<img width="1306" alt="Screen Shot 2022-11-28 at 5 33 00 PM" src="https://user-images.githubusercontent.com/54825214/204394971-9a38e211-0308-4756-80fd-e9bb18740024.png">

**Comment by dsert1** [comment]
Maybe all we need to do is specify in some fine print somewhere that only the US is supported for the beta

**Comment by an-bo-chen** [comment]
I actually fixed this issue by throwing an error if the location does not exist yet. Should I merge now and after I finished Reviews?

**Comment by dsert1** [comment]
Super sounds good
